apiVersion: apps/v1
kind: Deployment
metadata:
  name: monapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monapp
  template:
    metadata:
      labels:
        app: monapp
    spec:
      containers:
        - name: monapp
          image: imanehl13/SpringBootAppDeploy:1.0
          ports:
            - containerPort: 8080
